[package]
name = "nft-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1", features = ["v4"] }
tokio = { version = "1", features = ["full"] }
[dependencies.sqlx]
version = "0.6"
features = ["postgres", "offline"]
